columns:
  - name: "Network Tools"
    folder: "network_tools"
    description: "Various network utilities"
  - name: "File Operations"
    folder: "file_ops"
    description: "File management tools"
  - name: "System Info"
    folder: "system_info"
    description: "System information tools"